version: '3.6'

services:
    web:
        image: currentmap
        build: .
        command: /bin/bash -c ./start.sh
        working_dir: /app
        ports:
            - "8001:8001"
        volumes:
            - .:/app