version: '3.6'

services:
    web:
        image: currentmap
        build: .
        command: python manage.py runserver 0.0.0.0:8001
        working_dir: /app
        ports:
            - "8001:8001"
        volumes:
            - .:/app