# Generated by Django 4.1.5 on 2023-01-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('game', models.IntegerField(choices=[(0, 'TM2020'), (1, 'TM2'), (2, 'TMTURBO')])),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('author_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.CharField(max_length=64, unique=True)),
                ('current_pb', models.IntegerField(null=True)),
                ('current_map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.map')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128, null=True)),
                ('club_tag', models.CharField(max_length=128, null=True)),
                ('game', models.IntegerField(choices=[(0, 'TM2020'), (1, 'TM2'), (2, 'TMTURBO')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='api.player')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.group')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='api.player')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_groups', to='api.player'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='api.player'),
        ),
    ]
