# Generated by Django 4.1.5 on 2023-01-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeraccount',
            name='login',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
