# Generated by Django 4.1.5 on 2023-01-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_playeraccount_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeraccount',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_accounts', to='api.player'),
        ),
    ]
