# Generated by Django 4.1.5 on 2023-01-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_playeraccount_player'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playeraccount',
            unique_together={('player', 'game')},
        ),
    ]
