# Generated by Django 4.1.5 on 2023-01-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_map_game_alter_playeraccount_game'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playeraccount',
            unique_together={('player', 'game')},
        ),
        migrations.AlterField(
            model_name='playeraccount',
            name='login',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='playeraccount',
            unique_together={('player', 'game'), ('game', 'login')},
        ),
    ]
